In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [ ]:
## Movie Recommendation based on tags

# Creating DataFrame

In [2]:
credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movies.head(4)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106

In [4]:
credits.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [ ]:
# Merging both the dataframes 

In [5]:
movies = movies.merge(credits,on ='title')
movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0   
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0   
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count movie_id  \
0                                    Avatar          7.2      11800    19995   
1  Pirates of the Caribbean: At World's End          6.9       4500      285   
2                                   Spectre          6.3       4466   206647   
3                     The Dark Knight Rises          7.6       9106    49026   
4                               John Carter          6.1       2124    49529   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...

In [6]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [ ]:
## Droping 

In [45]:
# genres, movie_id, keywords, original_title, overview,cast, crew using these attributes we will create tags 
# with which we will recommend movies of similar tags 

In [7]:
movies = movies[['movie_id','original_title','genres', 'keywords', 'overview','cast', 'crew']]
movies.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

# Data Cleaning 

## Removing Null Values 

In [8]:
movies.isna().sum()

movie_id          0
original_title    0
genres            0
keywords          0
overview          3
cast              0
crew              0
dtype: int64

In [9]:
movies[movies['overview'].isna()]

movie_id                              original_title  \
2662    370980  Chiamatemi Francesco - Il Papa della gente   
4147    459488                 To Be Frank, Sinatra at 100   
4437    292539                                 Food Chains   

                                   genres  \
2662        [{"id": 18, "name": "Drama"}]   
4147  [{"id": 99, "name": "Documentary"}]   
4437  [{"id": 99, "name": "Documentary"}]   

                                               keywords overview  \
2662  [{"id": 717, "name": "pope"}, {"id": 5565, "na...      NaN   
4147  [{"id": 6027, "name": "music"}, {"id": 225822,...      NaN   
4437                                                 []      NaN   

                                                   cast  \
2662  [{"cast_id": 5, "character": "Jorge Mario Berg...   
4147  [{"cast_id": 0, "character": "Narrator", "cred...   
4437                                                 []   

                                                   crew  
2662  [{"credit_id": "5660019ac3a36875f100252b", "de...  
4147  [{"credit_id": "592b25e4c3a368783e065a2f", "de...  
4437  [{"credit_id": "5470c3b1c3a368085e000abd", "de...

In [10]:
# AS the null values are present only in 3 rows we will drop it 
movies = movies.dropna()

## processing string input into tags format

In [11]:
# these two attributes are in string format but we need it to be in dict format to extract name of genres 
print(type(movies['genres'][0]))
print(type(movies['keywords'][0]))

<class 'str'>
<class 'str'>


In [ ]:
## Converting movies names to lower case to make 
x = lambda a:a.lower()
movies['original_title'] = movies['original_title'].apply(x)

In [12]:
from ast import literal_eval

In [13]:
def conversion(x):
    array = np.array([])
    for i in literal_eval(x):
        array = np.append(array,i['name'])
    return array

In [14]:
movies['genres'] = movies['genres'].apply(conversion)
movies.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [14]:
## Same process can be repeated for keywords as we are only interested in names 

In [15]:
movies['keywords'] = movies['keywords'].apply(conversion)
movies.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [ ]:
# for cast we will take first 2 actors as they would be in lead roles of the movie 

In [16]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 

In [17]:
def conversion_cast(x):
    array = np.array([])
    count = 0

    for i in literal_eval(x):

        if count < 2:
            array = np.append(array, i['name'])
            count += 1

        if count == 2:
            break
    return array

In [18]:
movies['cast'] = movies['cast'].apply(conversion_cast)
movies.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                              cast  \
0   [Sam Worthington, Zoe Saldana]   
1     [Johnny Depp, Orlando Bloom]   
2  [Daniel Craig, Christoph Waltz]   
3  [Christian Bale, Michael Caine]   
4    [Taylor Kitsch, Lynn Collins]   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [19]:
def conversion_crew(x):
    
    for i in literal_eval(x):
        
        if (i['job']) == 'Director':
            return [i['name']]

In [20]:
movies['crew']  = movies['crew'].apply(conversion_crew)
movies.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                              cast                 crew  
0   [Sam Worthington, Zoe Saldana]      [James Cameron]  
1     [Johnny Depp, Orlando Bloom]     [Gore Verbinski]  
2  [Daniel Craig, Christoph Waltz]         [Sam Mendes]  
3  [Christian Bale, Michael Caine]  [Christopher Nolan]  
4    [Taylor Kitsch, Lynn Collins]     [Andrew Stanton]

In [149]:
# Now converting owerview into list of words to get tags 

In [21]:
splitting = lambda a:(a.split()) 
movies['overview'] = movies['overview'].apply(splitting)

In [22]:
movies.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                              cast                 crew  
0   [Sam Worthington, Zoe Saldana]      [James Cameron]  
1     [Johnny Depp, Orlando Bloom]     [Gore Verbinski]  
2  [Daniel Craig, Christoph Waltz]         [Sam Mendes]  
3  [Christian Bale, Michael Caine]  [Christopher Nolan]  
4    [Taylor Kitsch, Lynn Collins]     [Andrew Stanton]

In [ ]:
# Removing spaces between words in each tag 

In [23]:
def space_removal(x):
    l =[]
    for i in x:
        l.append(i.replace(" ",""))    
    return l

In [24]:
def space_removal_crew(x):
    l = []
    for i in x:            
        if type(i) != 'NoneType':
            l.append(i.replace(" ",""))
    return l 

In [25]:
movies['cast'] = movies['cast'].apply(space_removal)
movies['genres'] = movies['genres'].apply(space_removal)
movies['keywords'] = movies['keywords'].apply(space_removal)

In [26]:
movies[movies['crew'].isna()]
# there are some na values in crew table so we are droping it 

movie_id                                     original_title  \
3669     19615                                          Flying By   
3678    447027                                    Running Forever   
3736     26379                                                Paa   
3984     55831                                 Boynton Beach Club   
4075    371085                                          Sharkskin   
4112     48382    The Book of Mormon Movie, Volume 1: The Journey   
4125    325140                             Hum To Mohabbat Karega   
4130     20653                                     Roadside Romeo   
4254    361505                              Me You and Five Bucks   
4311    114065                          Down & Out With The Dolls   
4320    137955                                          Crowsnest   
4328    102840                                 Sex With Strangers   
4380     47686                              Dream with the Fishes   
4407     43630                                The Helix... Loaded   
4411    357441                                  Karachi se Lahore   
4464    279759                                Harrison Montgomery   
4510    331493                            Light from the Darkroom   
4559    380097                         America Is Still the Place   
4568    297100                           The Little Ponderosa Zoo   
4572    325579                                       Diamond Ruff   
4577    328307  Rise of the Entrepreneur: The Search for a Bet...   
4589     47546                                  I Want Your Money   
4595     43743                                             Fabled   
4639    300327                                        Death Calls   
4644    378237                           Amidst the Devil's Wings   
4650    325123                                    Teeth and Blood   
4663    320435                                          UnDivided   
4668     40963                                     Little Big Top   
4680    194588                   Short Cut to Nirvana: Kumbh Mela   
4722     38786  The Blood of My Brother: A Story of Death in Iraq   

                                                 genres           keywords  \
3669  [[, {, ", i, d, ", :, , 1, 8, ,, , ", n, a, m,...                 []   
3678  [[, {, ", i, d, ", :, , 1, 0, 7, 5, 1, ,, , ",...                 []   
3736  [[, {, ", i, d, ", :, , 1, 8, ,, , ", n, a, m,...                 []   
3984  [[, {, ", i, d, ", :, , 3, 5, ,, , ", n, a, m,...  [independentfilm]   
4075                                             [[, ]]                 []   
4112                                             [[, ]]                 []   
4125                                             [[, ]]                 []   
4130  [[, {, ", i, d, ", :, , 1, 6, ,, , ", n, a, m,...                 []   
4254  [[, {, ", i, d, ", :, , 1, 0, 7, 4, 9, ,, , ",...                 []   
4311  [[, {, ", i, d, ", :, , 3, 5, ,, , ", n, a, m,...                 []   
4320                                             [[, ]]                 []   
4328  [[, {, ", i, d, ", :, , 9, 9, ,, , ", n, a, m,...                 []   
4380  [[, {, ", i, d, ", :, , 3, 5, ,, , ", n, a, m,...  [independentfilm]   
4407  [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...                 []   
4411  [[, {, ", i, d, ", :, , 1, 0, 7, 5, 1, ,, , ",...                 []   
4464                                             [[, ]]                 []   
4510                                             [[, ]]                 []   
4559                                             [[, ]]                 []   
4568                                             [[, ]]                 []   
4572                                             [[, ]]                 []   
4577                                             [[, ]]                 []   
4589  [[, {, ", i, d, ", :, , 9, 9, ,, , ", n, a, m,...                 []   
4595  [[, {, ", i, d, ", :, , 1, 8, ,, , ", n, a, m,...  [independentfil

In [27]:
movies.dropna(inplace=True)
movies[movies['crew'].isna()]

Empty DataFrame
Columns: [movie_id, original_title, genres, keywords, overview, cast, crew]
Index: []

In [28]:
movies['crew'] = movies['crew'].apply(space_removal_crew)

In [ ]:
## Creating tags column

In [29]:
movies['tags'] = movies['overview'] + movies['keywords'] + movies['genres'] + movies['cast'] + movies['crew'] 
movies.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                              genres  \
0  [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...   
1  [[, {, ", i, d, ", :, , 1, 2, ,, , ", n, a, m,...   
2  [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...   
3  [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...   
4  [[, {, ", i, d, ", :, , 2, 8, ,, , ", n, a, m,...   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   
3  [dccomics, crimefighter, terrorist, secretiden...   
4  [basedonnovel, mars, medallion, spacetravel, p...   

                                            overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  [Captain, Barbossa,, long, believed, to, be, d...   
2  [A, cryptic, message, from, Bond’s, past, send...   
3  [Following, the, death, of, District, Attorney...   
4  [John, Carter, is, a, war-weary,, former, mili...   

                            cast                crew  \
0   [SamWorthington, ZoeSaldana]      [JamesCameron]   
1     [JohnnyDepp, OrlandoBloom]     [GoreVerbinski]   
2  [DanielCraig, ChristophWaltz]         [SamMendes]   
3  [ChristianBale, MichaelCaine]  [ChristopherNolan]   
4    [TaylorKitsch, LynnCollins]     [AndrewStanton]   

                                                tags  
0  [In, the, 22nd, century,, a, paraplegic, Marin...  
1  [Captain, Barbossa,, long, believed, to, be, d...  
2  [A, cryptic, message, from, Bond’s, past, send...  
3  [Following, the, death, of, District, Attorney...  
4  [John, Carter, is, a, war-weary,, former, mili...

In [30]:
# removing comas and making it lower case 
movies['tags'] = movies['tags'].apply(lambda x:" ".join(x).lower())

In [31]:
movies = movies[['movie_id','original_title','tags']]
movies.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...  
3  following the death of district attorney harve...  
4  john carter is a war-weary, former military ca...

### Text Processing of tags

In [32]:
from nltk.corpus import stopwords
from nltk import PorterStemmer

p = PorterStemmer()

In [129]:
#nltk.download('stopwords')

In [ ]:
## Removal of stopwords
## Steming of words so that tags like 'action' or 'actions' would become one tag

In [33]:
tags = movies['tags'].copy()
tags

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...                        
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4776, dtype: object

In [34]:
i = 0
for sentence in tags:
    l = []
    for word in sentence.split():
        if word not in stopwords.words('english'):
            l.append(p.stem(word))

    movies['tags'][i] = ' '.join(l)
    i = i + 1

C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\U

C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\Users\knikh\AppData\Local\Temp\ipykernel_10308\1516925473.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'][i] = ' '.join(l)
C:\U

In [35]:
movies['tags']

0       22nd century, parapleg marin dispatch moon pan...
1       captain barbossa, long believ dead, come back ...
2       cryptic messag bond’ past send trail uncov sin...
3       follow death district attorney harvey dent, ba...
4       john carter war-weary, former militari captain...
                              ...                        
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4776, dtype: object

In [36]:
movies.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  
0  22nd century, parapleg marin dispatch moon pan...  
1  captain barbossa, long believ dead, come back ...  
2  cryptic messag bond’ past send trail uncov sin...  
3  follow death district attorney harvey dent, ba...  
4  john carter war-weary, former militari captain...

## Creating vectors using bag of words

In [37]:
from sklearn.feature_extraction import text

In [205]:
cv = text.CountVectorizer(max_features=10000)
vec = cv.fit_transform(movies['tags'])

In [206]:
vec = vec.toarray()

In [211]:
cv.get_feature_names()

['00',
 '000',
 '007',
 '10',
 '100',
 '10th',
 '11',
 '12',
 '12th',
 '13',
 '14',
 '15',
 '150',
 '15th',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '1863',
 '1890',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1927',
 '1930',
 '1930s',
 '1937',
 '1940',
 '1940s',
 '1941',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1979',
 '1980',
 '1980s',
 '1984',
 '1985',
 '1986',
 '1987',
 '1990',
 '1994',
 '1995',
 '1996',
 '1997',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2007',
 '2008',
 '2009',
 '2012',
 '20th',
 '21st',
 '21stcenturi',
 '22nd',
 '23',
 '24',
 '25',
 '27',
 '28',
 '29',
 '30',
 '300',
 '35',
 '3d',
 '40',
 '400',
 '47',
 '4th',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '70',
 '7th',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abbi',
 'abbiecornish',
 'abduct',
 'abigailbreslin',


In [212]:
print(vec)
print('\n')
print(vec.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(4776, 10000)


In [ ]:
### In higher dimension Euclidean distance is not good so we will use Cosine Distance
### Cosine distance will gives us Theta, Smaller the theta the closer the other movie is to the 
### given movie and movie is very similar to given movie

In [213]:
from sklearn.metrics.pairwise import cosine_similarity


In [214]:
similarity_vec = cosine_similarity(vec)
similarity_vec

array([[1.        , 0.        , 0.02639818, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.02898855, ..., 0.01698089, 0.        ,
        0.        ],
       [0.02639818, 0.02898855, 1.        , ..., 0.01673655, 0.        ,
        0.        ],
       ...,
       [0.        , 0.01698089, 0.01673655, ..., 1.        , 0.36344868,
        0.2228006 ],
       [0.        , 0.        , 0.        , ..., 0.36344868, 1.        ,
        0.28392415],
       [0.        , 0.        , 0.        , ..., 0.2228006 , 0.28392415,
        1.        ]])

In [215]:
print(similarity_vec.shape)

(4776, 4776)


In [216]:
movies

movie_id                            original_title  \
0        19995                                    avatar   
1          285  pirates of the caribbean: at world's end   
2       206647                                   spectre   
3        49026                     the dark knight rises   
4        49529                               john carter   
...        ...                                       ...   
4804      9367                               el mariachi   
4805     72766                                 newlyweds   
4806    231617                 signed, sealed, delivered   
4807    126186                          shanghai calling   
4808     25975                         my date with drew   

                                                   tags  
0     22nd century, parapleg marin dispatch moon pan...  
1     captain barbossa, long believ dead, come back ...  
2     cryptic messag bond’ past send trail uncov sin...  
3     follow death district attorney harvey dent, ba...  
4     john carter war-weary, former militari captain...  
...                                                 ...  
4804  el mariachi just wants to play his guitar and ...  
4805  a newlywed couple's honeymoon is upended by th...  
4806  "signed, sealed, delivered" introduces a dedic...  
4807  when ambitious new york attorney sam is sent t...  
4808  ever since the second grade when he first saw ...  

[4776 rows x 3 columns]

In [217]:
def similarity_of_movies(movie_name):
    movie_name = movie_name.lower()
    index = movies.loc[movies['original_title']==movie_name].index[0]
    
    movie_indexes = np.arange(0, similarity_vec[index].shape[0],
                         dtype='int').reshape(-1, 1)
    
    stack = np.hstack((similarity_vec[index].reshape(-1, 1),movie_indexes))
    
    sorted_stack = stack[stack[:,0].argsort()][::-1]
    
    similar_movies_index = sorted_stack[1:6][:,1]
    print(similar_movies_index)
    
    similar_movies = list(movies.iloc[similar_movies_index,1])
    
    return similar_movies

In [222]:
gg = similarity_of_movies('how to train your dragon')
gg

[ 160. 1309.  746. 2449.  803.]


['how to train your dragon 2',
 "dragon nest: warriors' dawn",
 'reign of fire',
 'chasseurs de dragons',
 'dragonheart']

In [168]:
movies.to_csv('Movies_with_Tags.csv')

In [223]:
import pickle 

pickle.dump(similarity_vec,open('similarity_vec','wb'))

In [224]:
pickle.load(open('similarity_vec','rb'))

array([[1.        , 0.        , 0.02639818, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.02898855, ..., 0.01698089, 0.        ,
        0.        ],
       [0.02639818, 0.02898855, 1.        , ..., 0.01673655, 0.        ,
        0.        ],
       ...,
       [0.        , 0.01698089, 0.01673655, ..., 1.        , 0.36344868,
        0.2228006 ],
       [0.        , 0.        , 0.        , ..., 0.36344868, 1.        ,
        0.28392415],
       [0.        , 0.        , 0.        , ..., 0.2228006 , 0.28392415,
        1.        ]])